geometry:
  nml_file: ./namelist.atmosphere_240km
  streams_file: ./streams.atmosphere_240km

background:
  state variables:
  - stream_function
  - spechum
  - velocity_potential
  - temperature
  - surface_pressure
  filename: ./bg.nc
  date: 2026-06-22T00:00:00Z
  stream name: control
  transform model to analysis: false

input variables:
- stream_function
- spechum
- velocity_potential
- temperature
- surface_pressure

ensemble:
  members from template:
    template:
      filename: ../samples/PTB_f48mf24_%mem%.nc
      state variables:
      - stream_function
      - spechum
      - velocity_potential
      - temperature
      - surface_pressure
      date: 2026-06-22T00:00:00Z
      stream name: control
      transform model to analysis: false
    pattern: "%mem%"
    nmembers: 4
    zero padding: 3

inverse blocks:
- saber block name: BUMP_VerticalBalance
  read:
    io:
      files prefix: mpas
    drivers:
      read local sampling: true
      read global sampling: false
      read vertical balance: true
    vertical balance:
      vbal:
      - balanced variable: velocity_potential
        unbalanced variable: stream_function
        diagonal regression: true
      - balanced variable: temperature
        unbalanced variable: stream_function
      - balanced variable: surface_pressure
        unbalanced variable: stream_function
      pseudo inverse: true
      dominant mode: 20

output:
  filename: ../samplesUnbalanced/PTB_f48mf24_%{member}%.nc
  date: 2026-06-22T00:00:00Z
  stream name: control
